class NotLoggedInError(Exception):
    pass


class InvalidCall(Exception):
    pass
