def UrlError(Exception):
    pass


def MessageError(Exception):
    pass